// Code generated by ent, DO NOT EDIT.

package charge

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the charge type in the database.
	Label = "charge"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerUserID holds the string denoting the owner_user_id field in the database.
	FieldOwnerUserID = "owner_user_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldContractID holds the string denoting the contract_id field in the database.
	FieldContractID = "contract_id"
	// FieldMilestoneID holds the string denoting the milestone_id field in the database.
	FieldMilestoneID = "milestone_id"
	// FieldChargeType holds the string denoting the charge_type field in the database.
	FieldChargeType = "charge_type"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDueDate holds the string denoting the due_date field in the database.
	FieldDueDate = "due_date"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldPaymentLink holds the string denoting the payment_link field in the database.
	FieldPaymentLink = "payment_link"
	// FieldQrCode holds the string denoting the qr_code field in the database.
	FieldQrCode = "qr_code"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the charge in the database.
	Table = "charges"
)

// Columns holds all SQL columns for charge fields.
var Columns = []string{
	FieldID,
	FieldOwnerUserID,
	FieldCustomerID,
	FieldContractID,
	FieldMilestoneID,
	FieldChargeType,
	FieldAmountCents,
	FieldCurrency,
	FieldPaymentMethod,
	FieldStatus,
	FieldDueDate,
	FieldPaidAt,
	FieldExternalID,
	FieldPaymentLink,
	FieldQrCode,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OwnerUserIDValidator is a validator for the "owner_user_id" field. It is called by the builders before save.
	OwnerUserIDValidator func(string) error
	// CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	CustomerIDValidator func(string) error
	// DefaultChargeType holds the default value on creation for the "charge_type" field.
	DefaultChargeType string
	// ChargeTypeValidator is a validator for the "charge_type" field. It is called by the builders before save.
	ChargeTypeValidator func(string) error
	// AmountCentsValidator is a validator for the "amount_cents" field. It is called by the builders before save.
	AmountCentsValidator func(uint64) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultPaymentMethod holds the default value on creation for the "payment_method" field.
	DefaultPaymentMethod string
	// PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	PaymentMethodValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultDueDate holds the default value on creation for the "due_date" field.
	DefaultDueDate func() time.Time
	// PaymentLinkValidator is a validator for the "payment_link" field. It is called by the builders before save.
	PaymentLinkValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Charge queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerUserID orders the results by the owner_user_id field.
func ByOwnerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerUserID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByContractID orders the results by the contract_id field.
func ByContractID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContractID, opts...).ToFunc()
}

// ByMilestoneID orders the results by the milestone_id field.
func ByMilestoneID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMilestoneID, opts...).ToFunc()
}

// ByChargeType orders the results by the charge_type field.
func ByChargeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChargeType, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDueDate orders the results by the due_date field.
func ByDueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueDate, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByPaymentLink orders the results by the payment_link field.
func ByPaymentLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentLink, opts...).ToFunc()
}

// ByQrCode orders the results by the qr_code field.
func ByQrCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQrCode, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
