// Code generated by ent, DO NOT EDIT.

package contractsignature

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldID, id))
}

// ContractID applies equality check predicate on the "contract_id" field. It's identical to ContractIDEQ.
func ContractID(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldContractID, v))
}

// ContractVersionID applies equality check predicate on the "contract_version_id" field. It's identical to ContractVersionIDEQ.
func ContractVersionID(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldContractVersionID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldProvider, v))
}

// ProviderDocID applies equality check predicate on the "provider_doc_id" field. It's identical to ProviderDocIDEQ.
func ProviderDocID(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldProviderDocID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldStatus, v))
}

// SignerName applies equality check predicate on the "signer_name" field. It's identical to SignerNameEQ.
func SignerName(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldSignerName, v))
}

// SignerEmail applies equality check predicate on the "signer_email" field. It's identical to SignerEmailEQ.
func SignerEmail(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldSignerEmail, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedIP applies equality check predicate on the "accepted_ip" field. It's identical to AcceptedIPEQ.
func AcceptedIP(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldAcceptedIP, v))
}

// PayloadJSON applies equality check predicate on the "payload_json" field. It's identical to PayloadJSONEQ.
func PayloadJSON(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldPayloadJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldUpdatedAt, v))
}

// ContractIDEQ applies the EQ predicate on the "contract_id" field.
func ContractIDEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldContractID, v))
}

// ContractIDNEQ applies the NEQ predicate on the "contract_id" field.
func ContractIDNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldContractID, v))
}

// ContractIDIn applies the In predicate on the "contract_id" field.
func ContractIDIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldContractID, vs...))
}

// ContractIDNotIn applies the NotIn predicate on the "contract_id" field.
func ContractIDNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldContractID, vs...))
}

// ContractIDGT applies the GT predicate on the "contract_id" field.
func ContractIDGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldContractID, v))
}

// ContractIDGTE applies the GTE predicate on the "contract_id" field.
func ContractIDGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldContractID, v))
}

// ContractIDLT applies the LT predicate on the "contract_id" field.
func ContractIDLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldContractID, v))
}

// ContractIDLTE applies the LTE predicate on the "contract_id" field.
func ContractIDLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldContractID, v))
}

// ContractIDContains applies the Contains predicate on the "contract_id" field.
func ContractIDContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldContractID, v))
}

// ContractIDHasPrefix applies the HasPrefix predicate on the "contract_id" field.
func ContractIDHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldContractID, v))
}

// ContractIDHasSuffix applies the HasSuffix predicate on the "contract_id" field.
func ContractIDHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldContractID, v))
}

// ContractIDEqualFold applies the EqualFold predicate on the "contract_id" field.
func ContractIDEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldContractID, v))
}

// ContractIDContainsFold applies the ContainsFold predicate on the "contract_id" field.
func ContractIDContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldContractID, v))
}

// ContractVersionIDEQ applies the EQ predicate on the "contract_version_id" field.
func ContractVersionIDEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldContractVersionID, v))
}

// ContractVersionIDNEQ applies the NEQ predicate on the "contract_version_id" field.
func ContractVersionIDNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldContractVersionID, v))
}

// ContractVersionIDIn applies the In predicate on the "contract_version_id" field.
func ContractVersionIDIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldContractVersionID, vs...))
}

// ContractVersionIDNotIn applies the NotIn predicate on the "contract_version_id" field.
func ContractVersionIDNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldContractVersionID, vs...))
}

// ContractVersionIDGT applies the GT predicate on the "contract_version_id" field.
func ContractVersionIDGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldContractVersionID, v))
}

// ContractVersionIDGTE applies the GTE predicate on the "contract_version_id" field.
func ContractVersionIDGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldContractVersionID, v))
}

// ContractVersionIDLT applies the LT predicate on the "contract_version_id" field.
func ContractVersionIDLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldContractVersionID, v))
}

// ContractVersionIDLTE applies the LTE predicate on the "contract_version_id" field.
func ContractVersionIDLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldContractVersionID, v))
}

// ContractVersionIDContains applies the Contains predicate on the "contract_version_id" field.
func ContractVersionIDContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldContractVersionID, v))
}

// ContractVersionIDHasPrefix applies the HasPrefix predicate on the "contract_version_id" field.
func ContractVersionIDHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldContractVersionID, v))
}

// ContractVersionIDHasSuffix applies the HasSuffix predicate on the "contract_version_id" field.
func ContractVersionIDHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldContractVersionID, v))
}

// ContractVersionIDIsNil applies the IsNil predicate on the "contract_version_id" field.
func ContractVersionIDIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldContractVersionID))
}

// ContractVersionIDNotNil applies the NotNil predicate on the "contract_version_id" field.
func ContractVersionIDNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldContractVersionID))
}

// ContractVersionIDEqualFold applies the EqualFold predicate on the "contract_version_id" field.
func ContractVersionIDEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldContractVersionID, v))
}

// ContractVersionIDContainsFold applies the ContainsFold predicate on the "contract_version_id" field.
func ContractVersionIDContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldContractVersionID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderDocIDEQ applies the EQ predicate on the "provider_doc_id" field.
func ProviderDocIDEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldProviderDocID, v))
}

// ProviderDocIDNEQ applies the NEQ predicate on the "provider_doc_id" field.
func ProviderDocIDNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldProviderDocID, v))
}

// ProviderDocIDIn applies the In predicate on the "provider_doc_id" field.
func ProviderDocIDIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldProviderDocID, vs...))
}

// ProviderDocIDNotIn applies the NotIn predicate on the "provider_doc_id" field.
func ProviderDocIDNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldProviderDocID, vs...))
}

// ProviderDocIDGT applies the GT predicate on the "provider_doc_id" field.
func ProviderDocIDGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldProviderDocID, v))
}

// ProviderDocIDGTE applies the GTE predicate on the "provider_doc_id" field.
func ProviderDocIDGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldProviderDocID, v))
}

// ProviderDocIDLT applies the LT predicate on the "provider_doc_id" field.
func ProviderDocIDLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldProviderDocID, v))
}

// ProviderDocIDLTE applies the LTE predicate on the "provider_doc_id" field.
func ProviderDocIDLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldProviderDocID, v))
}

// ProviderDocIDContains applies the Contains predicate on the "provider_doc_id" field.
func ProviderDocIDContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldProviderDocID, v))
}

// ProviderDocIDHasPrefix applies the HasPrefix predicate on the "provider_doc_id" field.
func ProviderDocIDHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldProviderDocID, v))
}

// ProviderDocIDHasSuffix applies the HasSuffix predicate on the "provider_doc_id" field.
func ProviderDocIDHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldProviderDocID, v))
}

// ProviderDocIDIsNil applies the IsNil predicate on the "provider_doc_id" field.
func ProviderDocIDIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldProviderDocID))
}

// ProviderDocIDNotNil applies the NotNil predicate on the "provider_doc_id" field.
func ProviderDocIDNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldProviderDocID))
}

// ProviderDocIDEqualFold applies the EqualFold predicate on the "provider_doc_id" field.
func ProviderDocIDEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldProviderDocID, v))
}

// ProviderDocIDContainsFold applies the ContainsFold predicate on the "provider_doc_id" field.
func ProviderDocIDContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldProviderDocID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldStatus, v))
}

// SignerNameEQ applies the EQ predicate on the "signer_name" field.
func SignerNameEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldSignerName, v))
}

// SignerNameNEQ applies the NEQ predicate on the "signer_name" field.
func SignerNameNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldSignerName, v))
}

// SignerNameIn applies the In predicate on the "signer_name" field.
func SignerNameIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldSignerName, vs...))
}

// SignerNameNotIn applies the NotIn predicate on the "signer_name" field.
func SignerNameNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldSignerName, vs...))
}

// SignerNameGT applies the GT predicate on the "signer_name" field.
func SignerNameGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldSignerName, v))
}

// SignerNameGTE applies the GTE predicate on the "signer_name" field.
func SignerNameGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldSignerName, v))
}

// SignerNameLT applies the LT predicate on the "signer_name" field.
func SignerNameLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldSignerName, v))
}

// SignerNameLTE applies the LTE predicate on the "signer_name" field.
func SignerNameLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldSignerName, v))
}

// SignerNameContains applies the Contains predicate on the "signer_name" field.
func SignerNameContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldSignerName, v))
}

// SignerNameHasPrefix applies the HasPrefix predicate on the "signer_name" field.
func SignerNameHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldSignerName, v))
}

// SignerNameHasSuffix applies the HasSuffix predicate on the "signer_name" field.
func SignerNameHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldSignerName, v))
}

// SignerNameIsNil applies the IsNil predicate on the "signer_name" field.
func SignerNameIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldSignerName))
}

// SignerNameNotNil applies the NotNil predicate on the "signer_name" field.
func SignerNameNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldSignerName))
}

// SignerNameEqualFold applies the EqualFold predicate on the "signer_name" field.
func SignerNameEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldSignerName, v))
}

// SignerNameContainsFold applies the ContainsFold predicate on the "signer_name" field.
func SignerNameContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldSignerName, v))
}

// SignerEmailEQ applies the EQ predicate on the "signer_email" field.
func SignerEmailEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldSignerEmail, v))
}

// SignerEmailNEQ applies the NEQ predicate on the "signer_email" field.
func SignerEmailNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldSignerEmail, v))
}

// SignerEmailIn applies the In predicate on the "signer_email" field.
func SignerEmailIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldSignerEmail, vs...))
}

// SignerEmailNotIn applies the NotIn predicate on the "signer_email" field.
func SignerEmailNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldSignerEmail, vs...))
}

// SignerEmailGT applies the GT predicate on the "signer_email" field.
func SignerEmailGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldSignerEmail, v))
}

// SignerEmailGTE applies the GTE predicate on the "signer_email" field.
func SignerEmailGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldSignerEmail, v))
}

// SignerEmailLT applies the LT predicate on the "signer_email" field.
func SignerEmailLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldSignerEmail, v))
}

// SignerEmailLTE applies the LTE predicate on the "signer_email" field.
func SignerEmailLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldSignerEmail, v))
}

// SignerEmailContains applies the Contains predicate on the "signer_email" field.
func SignerEmailContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldSignerEmail, v))
}

// SignerEmailHasPrefix applies the HasPrefix predicate on the "signer_email" field.
func SignerEmailHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldSignerEmail, v))
}

// SignerEmailHasSuffix applies the HasSuffix predicate on the "signer_email" field.
func SignerEmailHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldSignerEmail, v))
}

// SignerEmailIsNil applies the IsNil predicate on the "signer_email" field.
func SignerEmailIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldSignerEmail))
}

// SignerEmailNotNil applies the NotNil predicate on the "signer_email" field.
func SignerEmailNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldSignerEmail))
}

// SignerEmailEqualFold applies the EqualFold predicate on the "signer_email" field.
func SignerEmailEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldSignerEmail, v))
}

// SignerEmailContainsFold applies the ContainsFold predicate on the "signer_email" field.
func SignerEmailContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldSignerEmail, v))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldAcceptedAt, v))
}

// AcceptedAtIsNil applies the IsNil predicate on the "accepted_at" field.
func AcceptedAtIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldAcceptedAt))
}

// AcceptedAtNotNil applies the NotNil predicate on the "accepted_at" field.
func AcceptedAtNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldAcceptedAt))
}

// AcceptedIPEQ applies the EQ predicate on the "accepted_ip" field.
func AcceptedIPEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldAcceptedIP, v))
}

// AcceptedIPNEQ applies the NEQ predicate on the "accepted_ip" field.
func AcceptedIPNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldAcceptedIP, v))
}

// AcceptedIPIn applies the In predicate on the "accepted_ip" field.
func AcceptedIPIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldAcceptedIP, vs...))
}

// AcceptedIPNotIn applies the NotIn predicate on the "accepted_ip" field.
func AcceptedIPNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldAcceptedIP, vs...))
}

// AcceptedIPGT applies the GT predicate on the "accepted_ip" field.
func AcceptedIPGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldAcceptedIP, v))
}

// AcceptedIPGTE applies the GTE predicate on the "accepted_ip" field.
func AcceptedIPGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldAcceptedIP, v))
}

// AcceptedIPLT applies the LT predicate on the "accepted_ip" field.
func AcceptedIPLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldAcceptedIP, v))
}

// AcceptedIPLTE applies the LTE predicate on the "accepted_ip" field.
func AcceptedIPLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldAcceptedIP, v))
}

// AcceptedIPContains applies the Contains predicate on the "accepted_ip" field.
func AcceptedIPContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldAcceptedIP, v))
}

// AcceptedIPHasPrefix applies the HasPrefix predicate on the "accepted_ip" field.
func AcceptedIPHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldAcceptedIP, v))
}

// AcceptedIPHasSuffix applies the HasSuffix predicate on the "accepted_ip" field.
func AcceptedIPHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldAcceptedIP, v))
}

// AcceptedIPIsNil applies the IsNil predicate on the "accepted_ip" field.
func AcceptedIPIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldAcceptedIP))
}

// AcceptedIPNotNil applies the NotNil predicate on the "accepted_ip" field.
func AcceptedIPNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldAcceptedIP))
}

// AcceptedIPEqualFold applies the EqualFold predicate on the "accepted_ip" field.
func AcceptedIPEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldAcceptedIP, v))
}

// AcceptedIPContainsFold applies the ContainsFold predicate on the "accepted_ip" field.
func AcceptedIPContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldAcceptedIP, v))
}

// PayloadJSONEQ applies the EQ predicate on the "payload_json" field.
func PayloadJSONEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldPayloadJSON, v))
}

// PayloadJSONNEQ applies the NEQ predicate on the "payload_json" field.
func PayloadJSONNEQ(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldPayloadJSON, v))
}

// PayloadJSONIn applies the In predicate on the "payload_json" field.
func PayloadJSONIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldPayloadJSON, vs...))
}

// PayloadJSONNotIn applies the NotIn predicate on the "payload_json" field.
func PayloadJSONNotIn(vs ...string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldPayloadJSON, vs...))
}

// PayloadJSONGT applies the GT predicate on the "payload_json" field.
func PayloadJSONGT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldPayloadJSON, v))
}

// PayloadJSONGTE applies the GTE predicate on the "payload_json" field.
func PayloadJSONGTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldPayloadJSON, v))
}

// PayloadJSONLT applies the LT predicate on the "payload_json" field.
func PayloadJSONLT(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldPayloadJSON, v))
}

// PayloadJSONLTE applies the LTE predicate on the "payload_json" field.
func PayloadJSONLTE(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldPayloadJSON, v))
}

// PayloadJSONContains applies the Contains predicate on the "payload_json" field.
func PayloadJSONContains(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContains(FieldPayloadJSON, v))
}

// PayloadJSONHasPrefix applies the HasPrefix predicate on the "payload_json" field.
func PayloadJSONHasPrefix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasPrefix(FieldPayloadJSON, v))
}

// PayloadJSONHasSuffix applies the HasSuffix predicate on the "payload_json" field.
func PayloadJSONHasSuffix(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldHasSuffix(FieldPayloadJSON, v))
}

// PayloadJSONIsNil applies the IsNil predicate on the "payload_json" field.
func PayloadJSONIsNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIsNull(FieldPayloadJSON))
}

// PayloadJSONNotNil applies the NotNil predicate on the "payload_json" field.
func PayloadJSONNotNil() predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotNull(FieldPayloadJSON))
}

// PayloadJSONEqualFold applies the EqualFold predicate on the "payload_json" field.
func PayloadJSONEqualFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEqualFold(FieldPayloadJSON, v))
}

// PayloadJSONContainsFold applies the ContainsFold predicate on the "payload_json" field.
func PayloadJSONContainsFold(v string) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldContainsFold(FieldPayloadJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ContractSignature {
	return predicate.ContractSignature(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContractSignature) predicate.ContractSignature {
	return predicate.ContractSignature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContractSignature) predicate.ContractSignature {
	return predicate.ContractSignature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContractSignature) predicate.ContractSignature {
	return predicate.ContractSignature(sql.NotPredicates(p))
}
