// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/charge"
)

// Charge is the model entity for the Charge schema.
type Charge struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID string `json:"owner_user_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID string `json:"customer_id,omitempty"`
	// ContractID holds the value of the "contract_id" field.
	ContractID *string `json:"contract_id,omitempty"`
	// MilestoneID holds the value of the "milestone_id" field.
	MilestoneID *string `json:"milestone_id,omitempty"`
	// ChargeType holds the value of the "charge_type" field.
	ChargeType string `json:"charge_type,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents uint64 `json:"amount_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// PaymentMethod holds the value of the "payment_method" field.
	PaymentMethod string `json:"payment_method,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate time.Time `json:"due_date,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID *string `json:"external_id,omitempty"`
	// PaymentLink holds the value of the "payment_link" field.
	PaymentLink *string `json:"payment_link,omitempty"`
	// QrCode holds the value of the "qr_code" field.
	QrCode *string `json:"qr_code,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Charge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case charge.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case charge.FieldID, charge.FieldOwnerUserID, charge.FieldCustomerID, charge.FieldContractID, charge.FieldMilestoneID, charge.FieldChargeType, charge.FieldCurrency, charge.FieldPaymentMethod, charge.FieldStatus, charge.FieldExternalID, charge.FieldPaymentLink, charge.FieldQrCode, charge.FieldDescription:
			values[i] = new(sql.NullString)
		case charge.FieldDueDate, charge.FieldPaidAt, charge.FieldCreatedAt, charge.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Charge fields.
func (_m *Charge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case charge.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = string(value.String)
			}
		case charge.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.String
			}
		case charge.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = value.String
			}
		case charge.FieldContractID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contract_id", values[i])
			} else if value.Valid {
				_m.ContractID = new(string)
				*_m.ContractID = value.String
			}
		case charge.FieldMilestoneID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field milestone_id", values[i])
			} else if value.Valid {
				_m.MilestoneID = new(string)
				*_m.MilestoneID = value.String
			}
		case charge.FieldChargeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field charge_type", values[i])
			} else if value.Valid {
				_m.ChargeType = value.String
			}
		case charge.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = uint64(value.Int64)
			}
		case charge.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case charge.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				_m.PaymentMethod = value.String
			}
		case charge.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case charge.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = value.Time
			}
		case charge.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case charge.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = new(string)
				*_m.ExternalID = value.String
			}
		case charge.FieldPaymentLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_link", values[i])
			} else if value.Valid {
				_m.PaymentLink = new(string)
				*_m.PaymentLink = value.String
			}
		case charge.FieldQrCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_code", values[i])
			} else if value.Valid {
				_m.QrCode = new(string)
				*_m.QrCode = value.String
			}
		case charge.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case charge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case charge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Charge.
// This includes values selected through modifiers, order, etc.
func (_m *Charge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Charge.
// Note that you need to call Charge.Unwrap() before calling this method if this Charge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Charge) Update() *ChargeUpdateOne {
	return NewChargeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Charge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Charge) Unwrap() *Charge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Charge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Charge) String() string {
	var builder strings.Builder
	builder.WriteString("Charge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_user_id=")
	builder.WriteString(_m.OwnerUserID)
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(_m.CustomerID)
	builder.WriteString(", ")
	if v := _m.ContractID; v != nil {
		builder.WriteString("contract_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MilestoneID; v != nil {
		builder.WriteString("milestone_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("charge_type=")
	builder.WriteString(_m.ChargeType)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(_m.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("due_date=")
	builder.WriteString(_m.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExternalID; v != nil {
		builder.WriteString("external_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PaymentLink; v != nil {
		builder.WriteString("payment_link=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.QrCode; v != nil {
		builder.WriteString("qr_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Charges is a parsable slice of Charge.
type Charges []*Charge
