// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/contractsignature"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// ContractSignatureUpdate is the builder for updating ContractSignature entities.
type ContractSignatureUpdate struct {
	config
	hooks    []Hook
	mutation *ContractSignatureMutation
}

// Where appends a list predicates to the ContractSignatureUpdate builder.
func (_u *ContractSignatureUpdate) Where(ps ...predicate.ContractSignature) *ContractSignatureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *ContractSignatureUpdate) SetContractID(v string) *ContractSignatureUpdate {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableContractID(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetContractVersionID sets the "contract_version_id" field.
func (_u *ContractSignatureUpdate) SetContractVersionID(v string) *ContractSignatureUpdate {
	_u.mutation.SetContractVersionID(v)
	return _u
}

// SetNillableContractVersionID sets the "contract_version_id" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableContractVersionID(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetContractVersionID(*v)
	}
	return _u
}

// ClearContractVersionID clears the value of the "contract_version_id" field.
func (_u *ContractSignatureUpdate) ClearContractVersionID() *ContractSignatureUpdate {
	_u.mutation.ClearContractVersionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ContractSignatureUpdate) SetProvider(v string) *ContractSignatureUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableProvider(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderDocID sets the "provider_doc_id" field.
func (_u *ContractSignatureUpdate) SetProviderDocID(v string) *ContractSignatureUpdate {
	_u.mutation.SetProviderDocID(v)
	return _u
}

// SetNillableProviderDocID sets the "provider_doc_id" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableProviderDocID(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetProviderDocID(*v)
	}
	return _u
}

// ClearProviderDocID clears the value of the "provider_doc_id" field.
func (_u *ContractSignatureUpdate) ClearProviderDocID() *ContractSignatureUpdate {
	_u.mutation.ClearProviderDocID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContractSignatureUpdate) SetStatus(v string) *ContractSignatureUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableStatus(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSignerName sets the "signer_name" field.
func (_u *ContractSignatureUpdate) SetSignerName(v string) *ContractSignatureUpdate {
	_u.mutation.SetSignerName(v)
	return _u
}

// SetNillableSignerName sets the "signer_name" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableSignerName(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetSignerName(*v)
	}
	return _u
}

// ClearSignerName clears the value of the "signer_name" field.
func (_u *ContractSignatureUpdate) ClearSignerName() *ContractSignatureUpdate {
	_u.mutation.ClearSignerName()
	return _u
}

// SetSignerEmail sets the "signer_email" field.
func (_u *ContractSignatureUpdate) SetSignerEmail(v string) *ContractSignatureUpdate {
	_u.mutation.SetSignerEmail(v)
	return _u
}

// SetNillableSignerEmail sets the "signer_email" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableSignerEmail(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetSignerEmail(*v)
	}
	return _u
}

// ClearSignerEmail clears the value of the "signer_email" field.
func (_u *ContractSignatureUpdate) ClearSignerEmail() *ContractSignatureUpdate {
	_u.mutation.ClearSignerEmail()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *ContractSignatureUpdate) SetAcceptedAt(v time.Time) *ContractSignatureUpdate {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableAcceptedAt(v *time.Time) *ContractSignatureUpdate {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *ContractSignatureUpdate) ClearAcceptedAt() *ContractSignatureUpdate {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetAcceptedIP sets the "accepted_ip" field.
func (_u *ContractSignatureUpdate) SetAcceptedIP(v string) *ContractSignatureUpdate {
	_u.mutation.SetAcceptedIP(v)
	return _u
}

// SetNillableAcceptedIP sets the "accepted_ip" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillableAcceptedIP(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetAcceptedIP(*v)
	}
	return _u
}

// ClearAcceptedIP clears the value of the "accepted_ip" field.
func (_u *ContractSignatureUpdate) ClearAcceptedIP() *ContractSignatureUpdate {
	_u.mutation.ClearAcceptedIP()
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *ContractSignatureUpdate) SetPayloadJSON(v string) *ContractSignatureUpdate {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *ContractSignatureUpdate) SetNillablePayloadJSON(v *string) *ContractSignatureUpdate {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// ClearPayloadJSON clears the value of the "payload_json" field.
func (_u *ContractSignatureUpdate) ClearPayloadJSON() *ContractSignatureUpdate {
	_u.mutation.ClearPayloadJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContractSignatureUpdate) SetUpdatedAt(v time.Time) *ContractSignatureUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ContractSignatureMutation object of the builder.
func (_u *ContractSignatureUpdate) Mutation() *ContractSignatureMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContractSignatureUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSignatureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContractSignatureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSignatureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContractSignatureUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contractsignature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSignatureUpdate) check() error {
	if v, ok := _u.mutation.ContractID(); ok {
		if err := contractsignature.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := contractsignature.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := contractsignature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AcceptedIP(); ok {
		if err := contractsignature.AcceptedIPValidator(v); err != nil {
			return &ValidationError{Name: "accepted_ip", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.accepted_ip": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSignatureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsignature.Table, contractsignature.Columns, sqlgraph.NewFieldSpec(contractsignature.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(contractsignature.FieldContractID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractVersionID(); ok {
		_spec.SetField(contractsignature.FieldContractVersionID, field.TypeString, value)
	}
	if _u.mutation.ContractVersionIDCleared() {
		_spec.ClearField(contractsignature.FieldContractVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(contractsignature.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderDocID(); ok {
		_spec.SetField(contractsignature.FieldProviderDocID, field.TypeString, value)
	}
	if _u.mutation.ProviderDocIDCleared() {
		_spec.ClearField(contractsignature.FieldProviderDocID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(contractsignature.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignerName(); ok {
		_spec.SetField(contractsignature.FieldSignerName, field.TypeString, value)
	}
	if _u.mutation.SignerNameCleared() {
		_spec.ClearField(contractsignature.FieldSignerName, field.TypeString)
	}
	if value, ok := _u.mutation.SignerEmail(); ok {
		_spec.SetField(contractsignature.FieldSignerEmail, field.TypeString, value)
	}
	if _u.mutation.SignerEmailCleared() {
		_spec.ClearField(contractsignature.FieldSignerEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(contractsignature.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(contractsignature.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedIP(); ok {
		_spec.SetField(contractsignature.FieldAcceptedIP, field.TypeString, value)
	}
	if _u.mutation.AcceptedIPCleared() {
		_spec.ClearField(contractsignature.FieldAcceptedIP, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(contractsignature.FieldPayloadJSON, field.TypeString, value)
	}
	if _u.mutation.PayloadJSONCleared() {
		_spec.ClearField(contractsignature.FieldPayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contractsignature.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsignature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContractSignatureUpdateOne is the builder for updating a single ContractSignature entity.
type ContractSignatureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContractSignatureMutation
}

// SetContractID sets the "contract_id" field.
func (_u *ContractSignatureUpdateOne) SetContractID(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableContractID(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetContractVersionID sets the "contract_version_id" field.
func (_u *ContractSignatureUpdateOne) SetContractVersionID(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetContractVersionID(v)
	return _u
}

// SetNillableContractVersionID sets the "contract_version_id" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableContractVersionID(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetContractVersionID(*v)
	}
	return _u
}

// ClearContractVersionID clears the value of the "contract_version_id" field.
func (_u *ContractSignatureUpdateOne) ClearContractVersionID() *ContractSignatureUpdateOne {
	_u.mutation.ClearContractVersionID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ContractSignatureUpdateOne) SetProvider(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableProvider(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderDocID sets the "provider_doc_id" field.
func (_u *ContractSignatureUpdateOne) SetProviderDocID(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetProviderDocID(v)
	return _u
}

// SetNillableProviderDocID sets the "provider_doc_id" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableProviderDocID(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetProviderDocID(*v)
	}
	return _u
}

// ClearProviderDocID clears the value of the "provider_doc_id" field.
func (_u *ContractSignatureUpdateOne) ClearProviderDocID() *ContractSignatureUpdateOne {
	_u.mutation.ClearProviderDocID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContractSignatureUpdateOne) SetStatus(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableStatus(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSignerName sets the "signer_name" field.
func (_u *ContractSignatureUpdateOne) SetSignerName(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetSignerName(v)
	return _u
}

// SetNillableSignerName sets the "signer_name" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableSignerName(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetSignerName(*v)
	}
	return _u
}

// ClearSignerName clears the value of the "signer_name" field.
func (_u *ContractSignatureUpdateOne) ClearSignerName() *ContractSignatureUpdateOne {
	_u.mutation.ClearSignerName()
	return _u
}

// SetSignerEmail sets the "signer_email" field.
func (_u *ContractSignatureUpdateOne) SetSignerEmail(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetSignerEmail(v)
	return _u
}

// SetNillableSignerEmail sets the "signer_email" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableSignerEmail(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetSignerEmail(*v)
	}
	return _u
}

// ClearSignerEmail clears the value of the "signer_email" field.
func (_u *ContractSignatureUpdateOne) ClearSignerEmail() *ContractSignatureUpdateOne {
	_u.mutation.ClearSignerEmail()
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *ContractSignatureUpdateOne) SetAcceptedAt(v time.Time) *ContractSignatureUpdateOne {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableAcceptedAt(v *time.Time) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *ContractSignatureUpdateOne) ClearAcceptedAt() *ContractSignatureUpdateOne {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetAcceptedIP sets the "accepted_ip" field.
func (_u *ContractSignatureUpdateOne) SetAcceptedIP(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetAcceptedIP(v)
	return _u
}

// SetNillableAcceptedIP sets the "accepted_ip" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillableAcceptedIP(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetAcceptedIP(*v)
	}
	return _u
}

// ClearAcceptedIP clears the value of the "accepted_ip" field.
func (_u *ContractSignatureUpdateOne) ClearAcceptedIP() *ContractSignatureUpdateOne {
	_u.mutation.ClearAcceptedIP()
	return _u
}

// SetPayloadJSON sets the "payload_json" field.
func (_u *ContractSignatureUpdateOne) SetPayloadJSON(v string) *ContractSignatureUpdateOne {
	_u.mutation.SetPayloadJSON(v)
	return _u
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_u *ContractSignatureUpdateOne) SetNillablePayloadJSON(v *string) *ContractSignatureUpdateOne {
	if v != nil {
		_u.SetPayloadJSON(*v)
	}
	return _u
}

// ClearPayloadJSON clears the value of the "payload_json" field.
func (_u *ContractSignatureUpdateOne) ClearPayloadJSON() *ContractSignatureUpdateOne {
	_u.mutation.ClearPayloadJSON()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContractSignatureUpdateOne) SetUpdatedAt(v time.Time) *ContractSignatureUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ContractSignatureMutation object of the builder.
func (_u *ContractSignatureUpdateOne) Mutation() *ContractSignatureMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContractSignatureUpdate builder.
func (_u *ContractSignatureUpdateOne) Where(ps ...predicate.ContractSignature) *ContractSignatureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContractSignatureUpdateOne) Select(field string, fields ...string) *ContractSignatureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContractSignature entity.
func (_u *ContractSignatureUpdateOne) Save(ctx context.Context) (*ContractSignature, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSignatureUpdateOne) SaveX(ctx context.Context) *ContractSignature {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContractSignatureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSignatureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContractSignatureUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contractsignature.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSignatureUpdateOne) check() error {
	if v, ok := _u.mutation.ContractID(); ok {
		if err := contractsignature.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.contract_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := contractsignature.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := contractsignature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AcceptedIP(); ok {
		if err := contractsignature.AcceptedIPValidator(v); err != nil {
			return &ValidationError{Name: "accepted_ip", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.accepted_ip": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSignatureUpdateOne) sqlSave(ctx context.Context) (_node *ContractSignature, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsignature.Table, contractsignature.Columns, sqlgraph.NewFieldSpec(contractsignature.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContractSignature.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contractsignature.FieldID)
		for _, f := range fields {
			if !contractsignature.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contractsignature.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(contractsignature.FieldContractID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractVersionID(); ok {
		_spec.SetField(contractsignature.FieldContractVersionID, field.TypeString, value)
	}
	if _u.mutation.ContractVersionIDCleared() {
		_spec.ClearField(contractsignature.FieldContractVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(contractsignature.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderDocID(); ok {
		_spec.SetField(contractsignature.FieldProviderDocID, field.TypeString, value)
	}
	if _u.mutation.ProviderDocIDCleared() {
		_spec.ClearField(contractsignature.FieldProviderDocID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(contractsignature.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SignerName(); ok {
		_spec.SetField(contractsignature.FieldSignerName, field.TypeString, value)
	}
	if _u.mutation.SignerNameCleared() {
		_spec.ClearField(contractsignature.FieldSignerName, field.TypeString)
	}
	if value, ok := _u.mutation.SignerEmail(); ok {
		_spec.SetField(contractsignature.FieldSignerEmail, field.TypeString, value)
	}
	if _u.mutation.SignerEmailCleared() {
		_spec.ClearField(contractsignature.FieldSignerEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(contractsignature.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(contractsignature.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AcceptedIP(); ok {
		_spec.SetField(contractsignature.FieldAcceptedIP, field.TypeString, value)
	}
	if _u.mutation.AcceptedIPCleared() {
		_spec.ClearField(contractsignature.FieldAcceptedIP, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadJSON(); ok {
		_spec.SetField(contractsignature.FieldPayloadJSON, field.TypeString, value)
	}
	if _u.mutation.PayloadJSONCleared() {
		_spec.ClearField(contractsignature.FieldPayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contractsignature.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ContractSignature{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsignature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
