// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/contractsignature"
)

// ContractSignature is the model entity for the ContractSignature schema.
type ContractSignature struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ContractID holds the value of the "contract_id" field.
	ContractID string `json:"contract_id,omitempty"`
	// ContractVersionID holds the value of the "contract_version_id" field.
	ContractVersionID *string `json:"contract_version_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderDocID holds the value of the "provider_doc_id" field.
	ProviderDocID *string `json:"provider_doc_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SignerName holds the value of the "signer_name" field.
	SignerName *string `json:"signer_name,omitempty"`
	// SignerEmail holds the value of the "signer_email" field.
	SignerEmail *string `json:"signer_email,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// AcceptedIP holds the value of the "accepted_ip" field.
	AcceptedIP *string `json:"accepted_ip,omitempty"`
	// PayloadJSON holds the value of the "payload_json" field.
	PayloadJSON *string `json:"payload_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContractSignature) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contractsignature.FieldID, contractsignature.FieldContractID, contractsignature.FieldContractVersionID, contractsignature.FieldProvider, contractsignature.FieldProviderDocID, contractsignature.FieldStatus, contractsignature.FieldSignerName, contractsignature.FieldSignerEmail, contractsignature.FieldAcceptedIP, contractsignature.FieldPayloadJSON:
			values[i] = new(sql.NullString)
		case contractsignature.FieldAcceptedAt, contractsignature.FieldCreatedAt, contractsignature.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContractSignature fields.
func (_m *ContractSignature) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contractsignature.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = string(value.String)
			}
		case contractsignature.FieldContractID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contract_id", values[i])
			} else if value.Valid {
				_m.ContractID = value.String
			}
		case contractsignature.FieldContractVersionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contract_version_id", values[i])
			} else if value.Valid {
				_m.ContractVersionID = new(string)
				*_m.ContractVersionID = value.String
			}
		case contractsignature.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case contractsignature.FieldProviderDocID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_doc_id", values[i])
			} else if value.Valid {
				_m.ProviderDocID = new(string)
				*_m.ProviderDocID = value.String
			}
		case contractsignature.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case contractsignature.FieldSignerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signer_name", values[i])
			} else if value.Valid {
				_m.SignerName = new(string)
				*_m.SignerName = value.String
			}
		case contractsignature.FieldSignerEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signer_email", values[i])
			} else if value.Valid {
				_m.SignerEmail = new(string)
				*_m.SignerEmail = value.String
			}
		case contractsignature.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case contractsignature.FieldAcceptedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_ip", values[i])
			} else if value.Valid {
				_m.AcceptedIP = new(string)
				*_m.AcceptedIP = value.String
			}
		case contractsignature.FieldPayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_json", values[i])
			} else if value.Valid {
				_m.PayloadJSON = new(string)
				*_m.PayloadJSON = value.String
			}
		case contractsignature.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case contractsignature.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContractSignature.
// This includes values selected through modifiers, order, etc.
func (_m *ContractSignature) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ContractSignature.
// Note that you need to call ContractSignature.Unwrap() before calling this method if this ContractSignature
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContractSignature) Update() *ContractSignatureUpdateOne {
	return NewContractSignatureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContractSignature entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContractSignature) Unwrap() *ContractSignature {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContractSignature is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContractSignature) String() string {
	var builder strings.Builder
	builder.WriteString("ContractSignature(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("contract_id=")
	builder.WriteString(_m.ContractID)
	builder.WriteString(", ")
	if v := _m.ContractVersionID; v != nil {
		builder.WriteString("contract_version_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	if v := _m.ProviderDocID; v != nil {
		builder.WriteString("provider_doc_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SignerName; v != nil {
		builder.WriteString("signer_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SignerEmail; v != nil {
		builder.WriteString("signer_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AcceptedIP; v != nil {
		builder.WriteString("accepted_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PayloadJSON; v != nil {
		builder.WriteString("payload_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContractSignatures is a parsable slice of ContractSignature.
type ContractSignatures []*ContractSignature
