// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/contractsignature"
)

// ContractSignatureCreate is the builder for creating a ContractSignature entity.
type ContractSignatureCreate struct {
	config
	mutation *ContractSignatureMutation
	hooks    []Hook
}

// SetContractID sets the "contract_id" field.
func (_c *ContractSignatureCreate) SetContractID(v string) *ContractSignatureCreate {
	_c.mutation.SetContractID(v)
	return _c
}

// SetContractVersionID sets the "contract_version_id" field.
func (_c *ContractSignatureCreate) SetContractVersionID(v string) *ContractSignatureCreate {
	_c.mutation.SetContractVersionID(v)
	return _c
}

// SetNillableContractVersionID sets the "contract_version_id" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableContractVersionID(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetContractVersionID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ContractSignatureCreate) SetProvider(v string) *ContractSignatureCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableProvider(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderDocID sets the "provider_doc_id" field.
func (_c *ContractSignatureCreate) SetProviderDocID(v string) *ContractSignatureCreate {
	_c.mutation.SetProviderDocID(v)
	return _c
}

// SetNillableProviderDocID sets the "provider_doc_id" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableProviderDocID(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetProviderDocID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ContractSignatureCreate) SetStatus(v string) *ContractSignatureCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableStatus(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSignerName sets the "signer_name" field.
func (_c *ContractSignatureCreate) SetSignerName(v string) *ContractSignatureCreate {
	_c.mutation.SetSignerName(v)
	return _c
}

// SetNillableSignerName sets the "signer_name" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableSignerName(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetSignerName(*v)
	}
	return _c
}

// SetSignerEmail sets the "signer_email" field.
func (_c *ContractSignatureCreate) SetSignerEmail(v string) *ContractSignatureCreate {
	_c.mutation.SetSignerEmail(v)
	return _c
}

// SetNillableSignerEmail sets the "signer_email" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableSignerEmail(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetSignerEmail(*v)
	}
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *ContractSignatureCreate) SetAcceptedAt(v time.Time) *ContractSignatureCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableAcceptedAt(v *time.Time) *ContractSignatureCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetAcceptedIP sets the "accepted_ip" field.
func (_c *ContractSignatureCreate) SetAcceptedIP(v string) *ContractSignatureCreate {
	_c.mutation.SetAcceptedIP(v)
	return _c
}

// SetNillableAcceptedIP sets the "accepted_ip" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableAcceptedIP(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetAcceptedIP(*v)
	}
	return _c
}

// SetPayloadJSON sets the "payload_json" field.
func (_c *ContractSignatureCreate) SetPayloadJSON(v string) *ContractSignatureCreate {
	_c.mutation.SetPayloadJSON(v)
	return _c
}

// SetNillablePayloadJSON sets the "payload_json" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillablePayloadJSON(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetPayloadJSON(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContractSignatureCreate) SetCreatedAt(v time.Time) *ContractSignatureCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableCreatedAt(v *time.Time) *ContractSignatureCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContractSignatureCreate) SetUpdatedAt(v time.Time) *ContractSignatureCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableUpdatedAt(v *time.Time) *ContractSignatureCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContractSignatureCreate) SetID(v string) *ContractSignatureCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContractSignatureCreate) SetNillableID(v *string) *ContractSignatureCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ContractSignatureMutation object of the builder.
func (_c *ContractSignatureCreate) Mutation() *ContractSignatureMutation {
	return _c.mutation
}

// Save creates the ContractSignature in the database.
func (_c *ContractSignatureCreate) Save(ctx context.Context) (*ContractSignature, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContractSignatureCreate) SaveX(ctx context.Context) *ContractSignature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractSignatureCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractSignatureCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContractSignatureCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := contractsignature.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := contractsignature.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contractsignature.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contractsignature.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := contractsignature.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContractSignatureCreate) check() error {
	if _, ok := _c.mutation.ContractID(); !ok {
		return &ValidationError{Name: "contract_id", err: errors.New(`ent: missing required field "ContractSignature.contract_id"`)}
	}
	if v, ok := _c.mutation.ContractID(); ok {
		if err := contractsignature.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.contract_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ContractSignature.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := contractsignature.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ContractSignature.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := contractsignature.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AcceptedIP(); ok {
		if err := contractsignature.AcceptedIPValidator(v); err != nil {
			return &ValidationError{Name: "accepted_ip", err: fmt.Errorf(`ent: validator failed for field "ContractSignature.accepted_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContractSignature.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ContractSignature.updated_at"`)}
	}
	return nil
}

func (_c *ContractSignatureCreate) sqlSave(ctx context.Context) (*ContractSignature, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ContractSignature.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContractSignatureCreate) createSpec() (*ContractSignature, *sqlgraph.CreateSpec) {
	var (
		_node = &ContractSignature{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contractsignature.Table, sqlgraph.NewFieldSpec(contractsignature.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ContractID(); ok {
		_spec.SetField(contractsignature.FieldContractID, field.TypeString, value)
		_node.ContractID = value
	}
	if value, ok := _c.mutation.ContractVersionID(); ok {
		_spec.SetField(contractsignature.FieldContractVersionID, field.TypeString, value)
		_node.ContractVersionID = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(contractsignature.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderDocID(); ok {
		_spec.SetField(contractsignature.FieldProviderDocID, field.TypeString, value)
		_node.ProviderDocID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(contractsignature.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SignerName(); ok {
		_spec.SetField(contractsignature.FieldSignerName, field.TypeString, value)
		_node.SignerName = &value
	}
	if value, ok := _c.mutation.SignerEmail(); ok {
		_spec.SetField(contractsignature.FieldSignerEmail, field.TypeString, value)
		_node.SignerEmail = &value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(contractsignature.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.AcceptedIP(); ok {
		_spec.SetField(contractsignature.FieldAcceptedIP, field.TypeString, value)
		_node.AcceptedIP = &value
	}
	if value, ok := _c.mutation.PayloadJSON(); ok {
		_spec.SetField(contractsignature.FieldPayloadJSON, field.TypeString, value)
		_node.PayloadJSON = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contractsignature.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contractsignature.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ContractSignatureCreateBulk is the builder for creating many ContractSignature entities in bulk.
type ContractSignatureCreateBulk struct {
	config
	err      error
	builders []*ContractSignatureCreate
}

// Save creates the ContractSignature entities in the database.
func (_c *ContractSignatureCreateBulk) Save(ctx context.Context) ([]*ContractSignature, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContractSignature, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContractSignatureMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContractSignatureCreateBulk) SaveX(ctx context.Context) []*ContractSignature {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractSignatureCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractSignatureCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
