// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/contractsignature"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// ContractSignatureDelete is the builder for deleting a ContractSignature entity.
type ContractSignatureDelete struct {
	config
	hooks    []Hook
	mutation *ContractSignatureMutation
}

// Where appends a list predicates to the ContractSignatureDelete builder.
func (_d *ContractSignatureDelete) Where(ps ...predicate.ContractSignature) *ContractSignatureDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContractSignatureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContractSignatureDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContractSignatureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contractsignature.Table, sqlgraph.NewFieldSpec(contractsignature.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContractSignatureDeleteOne is the builder for deleting a single ContractSignature entity.
type ContractSignatureDeleteOne struct {
	_d *ContractSignatureDelete
}

// Where appends a list predicates to the ContractSignatureDelete builder.
func (_d *ContractSignatureDeleteOne) Where(ps ...predicate.ContractSignature) *ContractSignatureDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContractSignatureDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contractsignature.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContractSignatureDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
