// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/contractversion"
)

// ContractVersionCreate is the builder for creating a ContractVersion entity.
type ContractVersionCreate struct {
	config
	mutation *ContractVersionMutation
	hooks    []Hook
}

// SetContractID sets the "contract_id" field.
func (_c *ContractVersionCreate) SetContractID(v string) *ContractVersionCreate {
	_c.mutation.SetContractID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ContractVersionCreate) SetVersion(v int) *ContractVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetTemplateName sets the "template_name" field.
func (_c *ContractVersionCreate) SetTemplateName(v string) *ContractVersionCreate {
	_c.mutation.SetTemplateName(v)
	return _c
}

// SetEditableContent sets the "editable_content" field.
func (_c *ContractVersionCreate) SetEditableContent(v string) *ContractVersionCreate {
	_c.mutation.SetEditableContent(v)
	return _c
}

// SetPdfURL sets the "pdf_url" field.
func (_c *ContractVersionCreate) SetPdfURL(v string) *ContractVersionCreate {
	_c.mutation.SetPdfURL(v)
	return _c
}

// SetNillablePdfURL sets the "pdf_url" field if the given value is not nil.
func (_c *ContractVersionCreate) SetNillablePdfURL(v *string) *ContractVersionCreate {
	if v != nil {
		_c.SetPdfURL(*v)
	}
	return _c
}

// SetEditableURL sets the "editable_url" field.
func (_c *ContractVersionCreate) SetEditableURL(v string) *ContractVersionCreate {
	_c.mutation.SetEditableURL(v)
	return _c
}

// SetNillableEditableURL sets the "editable_url" field if the given value is not nil.
func (_c *ContractVersionCreate) SetNillableEditableURL(v *string) *ContractVersionCreate {
	if v != nil {
		_c.SetEditableURL(*v)
	}
	return _c
}

// SetGeneratedAt sets the "generated_at" field.
func (_c *ContractVersionCreate) SetGeneratedAt(v time.Time) *ContractVersionCreate {
	_c.mutation.SetGeneratedAt(v)
	return _c
}

// SetNillableGeneratedAt sets the "generated_at" field if the given value is not nil.
func (_c *ContractVersionCreate) SetNillableGeneratedAt(v *time.Time) *ContractVersionCreate {
	if v != nil {
		_c.SetGeneratedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContractVersionCreate) SetCreatedAt(v time.Time) *ContractVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContractVersionCreate) SetNillableCreatedAt(v *time.Time) *ContractVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContractVersionCreate) SetID(v string) *ContractVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContractVersionCreate) SetNillableID(v *string) *ContractVersionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ContractVersionMutation object of the builder.
func (_c *ContractVersionCreate) Mutation() *ContractVersionMutation {
	return _c.mutation
}

// Save creates the ContractVersion in the database.
func (_c *ContractVersionCreate) Save(ctx context.Context) (*ContractVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContractVersionCreate) SaveX(ctx context.Context) *ContractVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContractVersionCreate) defaults() {
	if _, ok := _c.mutation.GeneratedAt(); !ok {
		v := contractversion.DefaultGeneratedAt()
		_c.mutation.SetGeneratedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contractversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := contractversion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContractVersionCreate) check() error {
	if _, ok := _c.mutation.ContractID(); !ok {
		return &ValidationError{Name: "contract_id", err: errors.New(`ent: missing required field "ContractVersion.contract_id"`)}
	}
	if v, ok := _c.mutation.ContractID(); ok {
		if err := contractversion.ContractIDValidator(v); err != nil {
			return &ValidationError{Name: "contract_id", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.contract_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ContractVersion.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := contractversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TemplateName(); !ok {
		return &ValidationError{Name: "template_name", err: errors.New(`ent: missing required field "ContractVersion.template_name"`)}
	}
	if v, ok := _c.mutation.TemplateName(); ok {
		if err := contractversion.TemplateNameValidator(v); err != nil {
			return &ValidationError{Name: "template_name", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.template_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EditableContent(); !ok {
		return &ValidationError{Name: "editable_content", err: errors.New(`ent: missing required field "ContractVersion.editable_content"`)}
	}
	if v, ok := _c.mutation.EditableContent(); ok {
		if err := contractversion.EditableContentValidator(v); err != nil {
			return &ValidationError{Name: "editable_content", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.editable_content": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PdfURL(); ok {
		if err := contractversion.PdfURLValidator(v); err != nil {
			return &ValidationError{Name: "pdf_url", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.pdf_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EditableURL(); ok {
		if err := contractversion.EditableURLValidator(v); err != nil {
			return &ValidationError{Name: "editable_url", err: fmt.Errorf(`ent: validator failed for field "ContractVersion.editable_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GeneratedAt(); !ok {
		return &ValidationError{Name: "generated_at", err: errors.New(`ent: missing required field "ContractVersion.generated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContractVersion.created_at"`)}
	}
	return nil
}

func (_c *ContractVersionCreate) sqlSave(ctx context.Context) (*ContractVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ContractVersion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContractVersionCreate) createSpec() (*ContractVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ContractVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contractversion.Table, sqlgraph.NewFieldSpec(contractversion.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ContractID(); ok {
		_spec.SetField(contractversion.FieldContractID, field.TypeString, value)
		_node.ContractID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(contractversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.TemplateName(); ok {
		_spec.SetField(contractversion.FieldTemplateName, field.TypeString, value)
		_node.TemplateName = value
	}
	if value, ok := _c.mutation.EditableContent(); ok {
		_spec.SetField(contractversion.FieldEditableContent, field.TypeString, value)
		_node.EditableContent = value
	}
	if value, ok := _c.mutation.PdfURL(); ok {
		_spec.SetField(contractversion.FieldPdfURL, field.TypeString, value)
		_node.PdfURL = &value
	}
	if value, ok := _c.mutation.EditableURL(); ok {
		_spec.SetField(contractversion.FieldEditableURL, field.TypeString, value)
		_node.EditableURL = &value
	}
	if value, ok := _c.mutation.GeneratedAt(); ok {
		_spec.SetField(contractversion.FieldGeneratedAt, field.TypeTime, value)
		_node.GeneratedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contractversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// ContractVersionCreateBulk is the builder for creating many ContractVersion entities in bulk.
type ContractVersionCreateBulk struct {
	config
	err      error
	builders []*ContractVersionCreate
}

// Save creates the ContractVersion entities in the database.
func (_c *ContractVersionCreateBulk) Save(ctx context.Context) ([]*ContractVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContractVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContractVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContractVersionCreateBulk) SaveX(ctx context.Context) []*ContractVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContractVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContractVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
