// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/integrationwebhookevent"
)

// IntegrationWebhookEventCreate is the builder for creating a IntegrationWebhookEvent entity.
type IntegrationWebhookEventCreate struct {
	config
	mutation *IntegrationWebhookEventMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *IntegrationWebhookEventCreate) SetProvider(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *IntegrationWebhookEventCreate) SetEventID(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetSignature sets the "signature" field.
func (_c *IntegrationWebhookEventCreate) SetSignature(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableSignature(v *string) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetSignature(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *IntegrationWebhookEventCreate) SetPayload(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IntegrationWebhookEventCreate) SetStatus(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableStatus(v *string) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *IntegrationWebhookEventCreate) SetReceivedAt(v time.Time) *IntegrationWebhookEventCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableReceivedAt(v *time.Time) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *IntegrationWebhookEventCreate) SetProcessedAt(v time.Time) *IntegrationWebhookEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableProcessedAt(v *time.Time) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntegrationWebhookEventCreate) SetCreatedAt(v time.Time) *IntegrationWebhookEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableCreatedAt(v *time.Time) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IntegrationWebhookEventCreate) SetID(v string) *IntegrationWebhookEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IntegrationWebhookEventCreate) SetNillableID(v *string) *IntegrationWebhookEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the IntegrationWebhookEventMutation object of the builder.
func (_c *IntegrationWebhookEventCreate) Mutation() *IntegrationWebhookEventMutation {
	return _c.mutation
}

// Save creates the IntegrationWebhookEvent in the database.
func (_c *IntegrationWebhookEventCreate) Save(ctx context.Context) (*IntegrationWebhookEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntegrationWebhookEventCreate) SaveX(ctx context.Context) *IntegrationWebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationWebhookEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationWebhookEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntegrationWebhookEventCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := integrationwebhookevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		v := integrationwebhookevent.DefaultReceivedAt()
		_c.mutation.SetReceivedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := integrationwebhookevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := integrationwebhookevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntegrationWebhookEventCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := integrationwebhookevent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "IntegrationWebhookEvent.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.event_id"`)}
	}
	if v, ok := _c.mutation.EventID(); ok {
		if err := integrationwebhookevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "IntegrationWebhookEvent.event_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Signature(); ok {
		if err := integrationwebhookevent.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "IntegrationWebhookEvent.signature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.payload"`)}
	}
	if v, ok := _c.mutation.Payload(); ok {
		if err := integrationwebhookevent.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "IntegrationWebhookEvent.payload": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := integrationwebhookevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IntegrationWebhookEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.received_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IntegrationWebhookEvent.created_at"`)}
	}
	return nil
}

func (_c *IntegrationWebhookEventCreate) sqlSave(ctx context.Context) (*IntegrationWebhookEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IntegrationWebhookEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntegrationWebhookEventCreate) createSpec() (*IntegrationWebhookEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &IntegrationWebhookEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(integrationwebhookevent.Table, sqlgraph.NewFieldSpec(integrationwebhookevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(integrationwebhookevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(integrationwebhookevent.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(integrationwebhookevent.FieldSignature, field.TypeString, value)
		_node.Signature = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(integrationwebhookevent.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(integrationwebhookevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(integrationwebhookevent.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(integrationwebhookevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(integrationwebhookevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// IntegrationWebhookEventCreateBulk is the builder for creating many IntegrationWebhookEvent entities in bulk.
type IntegrationWebhookEventCreateBulk struct {
	config
	err      error
	builders []*IntegrationWebhookEventCreate
}

// Save creates the IntegrationWebhookEvent entities in the database.
func (_c *IntegrationWebhookEventCreateBulk) Save(ctx context.Context) ([]*IntegrationWebhookEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntegrationWebhookEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntegrationWebhookEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntegrationWebhookEventCreateBulk) SaveX(ctx context.Context) []*IntegrationWebhookEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntegrationWebhookEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntegrationWebhookEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
