// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/milestone"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// MilestoneUpdate is the builder for updating Milestone entities.
type MilestoneUpdate struct {
	config
	hooks    []Hook
	mutation *MilestoneMutation
}

// Where appends a list predicates to the MilestoneUpdate builder.
func (_u *MilestoneUpdate) Where(ps ...predicate.Milestone) *MilestoneUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *MilestoneUpdate) SetProjectID(v string) *MilestoneUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableProjectID(v *string) *MilestoneUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *MilestoneUpdate) SetContractID(v string) *MilestoneUpdate {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableContractID(v *string) *MilestoneUpdate {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// ClearContractID clears the value of the "contract_id" field.
func (_u *MilestoneUpdate) ClearContractID() *MilestoneUpdate {
	_u.mutation.ClearContractID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *MilestoneUpdate) SetTitle(v string) *MilestoneUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableTitle(v *string) *MilestoneUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDeliverables sets the "deliverables" field.
func (_u *MilestoneUpdate) SetDeliverables(v string) *MilestoneUpdate {
	_u.mutation.SetDeliverables(v)
	return _u
}

// SetNillableDeliverables sets the "deliverables" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableDeliverables(v *string) *MilestoneUpdate {
	if v != nil {
		_u.SetDeliverables(*v)
	}
	return _u
}

// ClearDeliverables clears the value of the "deliverables" field.
func (_u *MilestoneUpdate) ClearDeliverables() *MilestoneUpdate {
	_u.mutation.ClearDeliverables()
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *MilestoneUpdate) SetAmountCents(v uint64) *MilestoneUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableAmountCents(v *uint64) *MilestoneUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *MilestoneUpdate) AddAmountCents(v uint64) *MilestoneUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// ClearAmountCents clears the value of the "amount_cents" field.
func (_u *MilestoneUpdate) ClearAmountCents() *MilestoneUpdate {
	_u.mutation.ClearAmountCents()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *MilestoneUpdate) SetDueDate(v time.Time) *MilestoneUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableDueDate(v *time.Time) *MilestoneUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *MilestoneUpdate) ClearDueDate() *MilestoneUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MilestoneUpdate) SetStatus(v string) *MilestoneUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MilestoneUpdate) SetNillableStatus(v *string) *MilestoneUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MilestoneUpdate) SetUpdatedAt(v time.Time) *MilestoneUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MilestoneMutation object of the builder.
func (_u *MilestoneUpdate) Mutation() *MilestoneMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MilestoneUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MilestoneUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MilestoneUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MilestoneUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MilestoneUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := milestone.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MilestoneUpdate) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := milestone.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Milestone.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := milestone.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Milestone.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := milestone.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Milestone.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MilestoneUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(milestone.Table, milestone.Columns, sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(milestone.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(milestone.FieldContractID, field.TypeString, value)
	}
	if _u.mutation.ContractIDCleared() {
		_spec.ClearField(milestone.FieldContractID, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(milestone.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Deliverables(); ok {
		_spec.SetField(milestone.FieldDeliverables, field.TypeString, value)
	}
	if _u.mutation.DeliverablesCleared() {
		_spec.ClearField(milestone.FieldDeliverables, field.TypeString)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(milestone.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(milestone.FieldAmountCents, field.TypeUint64, value)
	}
	if _u.mutation.AmountCentsCleared() {
		_spec.ClearField(milestone.FieldAmountCents, field.TypeUint64)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(milestone.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(milestone.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(milestone.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(milestone.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{milestone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MilestoneUpdateOne is the builder for updating a single Milestone entity.
type MilestoneUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MilestoneMutation
}

// SetProjectID sets the "project_id" field.
func (_u *MilestoneUpdateOne) SetProjectID(v string) *MilestoneUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableProjectID(v *string) *MilestoneUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *MilestoneUpdateOne) SetContractID(v string) *MilestoneUpdateOne {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableContractID(v *string) *MilestoneUpdateOne {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// ClearContractID clears the value of the "contract_id" field.
func (_u *MilestoneUpdateOne) ClearContractID() *MilestoneUpdateOne {
	_u.mutation.ClearContractID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *MilestoneUpdateOne) SetTitle(v string) *MilestoneUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableTitle(v *string) *MilestoneUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDeliverables sets the "deliverables" field.
func (_u *MilestoneUpdateOne) SetDeliverables(v string) *MilestoneUpdateOne {
	_u.mutation.SetDeliverables(v)
	return _u
}

// SetNillableDeliverables sets the "deliverables" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableDeliverables(v *string) *MilestoneUpdateOne {
	if v != nil {
		_u.SetDeliverables(*v)
	}
	return _u
}

// ClearDeliverables clears the value of the "deliverables" field.
func (_u *MilestoneUpdateOne) ClearDeliverables() *MilestoneUpdateOne {
	_u.mutation.ClearDeliverables()
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *MilestoneUpdateOne) SetAmountCents(v uint64) *MilestoneUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableAmountCents(v *uint64) *MilestoneUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *MilestoneUpdateOne) AddAmountCents(v uint64) *MilestoneUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// ClearAmountCents clears the value of the "amount_cents" field.
func (_u *MilestoneUpdateOne) ClearAmountCents() *MilestoneUpdateOne {
	_u.mutation.ClearAmountCents()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *MilestoneUpdateOne) SetDueDate(v time.Time) *MilestoneUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableDueDate(v *time.Time) *MilestoneUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *MilestoneUpdateOne) ClearDueDate() *MilestoneUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MilestoneUpdateOne) SetStatus(v string) *MilestoneUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MilestoneUpdateOne) SetNillableStatus(v *string) *MilestoneUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MilestoneUpdateOne) SetUpdatedAt(v time.Time) *MilestoneUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MilestoneMutation object of the builder.
func (_u *MilestoneUpdateOne) Mutation() *MilestoneMutation {
	return _u.mutation
}

// Where appends a list predicates to the MilestoneUpdate builder.
func (_u *MilestoneUpdateOne) Where(ps ...predicate.Milestone) *MilestoneUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MilestoneUpdateOne) Select(field string, fields ...string) *MilestoneUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Milestone entity.
func (_u *MilestoneUpdateOne) Save(ctx context.Context) (*Milestone, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MilestoneUpdateOne) SaveX(ctx context.Context) *Milestone {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MilestoneUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MilestoneUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MilestoneUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := milestone.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MilestoneUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := milestone.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Milestone.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := milestone.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Milestone.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := milestone.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Milestone.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MilestoneUpdateOne) sqlSave(ctx context.Context) (_node *Milestone, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(milestone.Table, milestone.Columns, sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Milestone.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, milestone.FieldID)
		for _, f := range fields {
			if !milestone.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != milestone.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(milestone.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(milestone.FieldContractID, field.TypeString, value)
	}
	if _u.mutation.ContractIDCleared() {
		_spec.ClearField(milestone.FieldContractID, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(milestone.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Deliverables(); ok {
		_spec.SetField(milestone.FieldDeliverables, field.TypeString, value)
	}
	if _u.mutation.DeliverablesCleared() {
		_spec.ClearField(milestone.FieldDeliverables, field.TypeString)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(milestone.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(milestone.FieldAmountCents, field.TypeUint64, value)
	}
	if _u.mutation.AmountCentsCleared() {
		_spec.ClearField(milestone.FieldAmountCents, field.TypeUint64)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(milestone.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(milestone.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(milestone.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(milestone.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Milestone{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{milestone.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
