// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/paymentevidence"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// PaymentEvidenceDelete is the builder for deleting a PaymentEvidence entity.
type PaymentEvidenceDelete struct {
	config
	hooks    []Hook
	mutation *PaymentEvidenceMutation
}

// Where appends a list predicates to the PaymentEvidenceDelete builder.
func (_d *PaymentEvidenceDelete) Where(ps ...predicate.PaymentEvidence) *PaymentEvidenceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PaymentEvidenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentEvidenceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PaymentEvidenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(paymentevidence.Table, sqlgraph.NewFieldSpec(paymentevidence.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PaymentEvidenceDeleteOne is the builder for deleting a single PaymentEvidence entity.
type PaymentEvidenceDeleteOne struct {
	_d *PaymentEvidenceDelete
}

// Where appends a list predicates to the PaymentEvidenceDelete builder.
func (_d *PaymentEvidenceDeleteOne) Where(ps ...predicate.PaymentEvidence) *PaymentEvidenceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PaymentEvidenceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{paymentevidence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PaymentEvidenceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
