// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/sagastate"
)

// SagaState is the model entity for the SagaState schema.
type SagaState struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ex: payment_saga
	SagaType string `json:"saga_type,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID string `json:"order_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents uint64 `json:"amount_cents,omitempty"`
	// CurrentStep holds the value of the "current_step" field.
	CurrentStep string `json:"current_step,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// ProviderRef holds the value of the "provider_ref" field.
	ProviderRef *string `json:"provider_ref,omitempty"`
	// FailureReason holds the value of the "failure_reason" field.
	FailureReason *string `json:"failure_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SagaState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sagastate.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case sagastate.FieldID, sagastate.FieldSagaType, sagastate.FieldOrderID, sagastate.FieldUserID, sagastate.FieldCurrentStep, sagastate.FieldStatus, sagastate.FieldIdempotencyKey, sagastate.FieldProviderRef, sagastate.FieldFailureReason:
			values[i] = new(sql.NullString)
		case sagastate.FieldCreatedAt, sagastate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SagaState fields.
func (_m *SagaState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sagastate.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = string(value.String)
			}
		case sagastate.FieldSagaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field saga_type", values[i])
			} else if value.Valid {
				_m.SagaType = value.String
			}
		case sagastate.FieldOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.String
			}
		case sagastate.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case sagastate.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				_m.AmountCents = uint64(value.Int64)
			}
		case sagastate.FieldCurrentStep:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_step", values[i])
			} else if value.Valid {
				_m.CurrentStep = value.String
			}
		case sagastate.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case sagastate.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case sagastate.FieldProviderRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_ref", values[i])
			} else if value.Valid {
				_m.ProviderRef = new(string)
				*_m.ProviderRef = value.String
			}
		case sagastate.FieldFailureReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failure_reason", values[i])
			} else if value.Valid {
				_m.FailureReason = new(string)
				*_m.FailureReason = value.String
			}
		case sagastate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sagastate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SagaState.
// This includes values selected through modifiers, order, etc.
func (_m *SagaState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SagaState.
// Note that you need to call SagaState.Unwrap() before calling this method if this SagaState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SagaState) Update() *SagaStateUpdateOne {
	return NewSagaStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SagaState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SagaState) Unwrap() *SagaState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SagaState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SagaState) String() string {
	var builder strings.Builder
	builder.WriteString("SagaState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("saga_type=")
	builder.WriteString(_m.SagaType)
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(_m.OrderID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("current_step=")
	builder.WriteString(_m.CurrentStep)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	if v := _m.ProviderRef; v != nil {
		builder.WriteString("provider_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailureReason; v != nil {
		builder.WriteString("failure_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SagaStates is a parsable slice of SagaState.
type SagaStates []*SagaState
