// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/predicate"
	"github.com/aggi-tech/aggipay/ent/servicecontract"
)

// ServiceContractUpdate is the builder for updating ServiceContract entities.
type ServiceContractUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceContractMutation
}

// Where appends a list predicates to the ServiceContractUpdate builder.
func (_u *ServiceContractUpdate) Where(ps ...predicate.ServiceContract) *ServiceContractUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ServiceContractUpdate) SetOwnerUserID(v string) *ServiceContractUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableOwnerUserID(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *ServiceContractUpdate) SetCustomerID(v string) *ServiceContractUpdate {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableCustomerID(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// SetContractType sets the "contract_type" field.
func (_u *ServiceContractUpdate) SetContractType(v string) *ServiceContractUpdate {
	_u.mutation.SetContractType(v)
	return _u
}

// SetNillableContractType sets the "contract_type" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableContractType(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetContractType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ServiceContractUpdate) SetTitle(v string) *ServiceContractUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableTitle(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *ServiceContractUpdate) SetAmountCents(v uint64) *ServiceContractUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableAmountCents(v *uint64) *ServiceContractUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *ServiceContractUpdate) AddAmountCents(v uint64) *ServiceContractUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetBillingType sets the "billing_type" field.
func (_u *ServiceContractUpdate) SetBillingType(v string) *ServiceContractUpdate {
	_u.mutation.SetBillingType(v)
	return _u
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableBillingType(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetBillingType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ServiceContractUpdate) SetStatus(v string) *ServiceContractUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableStatus(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ServiceContractUpdate) SetStartDate(v time.Time) *ServiceContractUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableStartDate(v *time.Time) *ServiceContractUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ServiceContractUpdate) SetEndDate(v time.Time) *ServiceContractUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableEndDate(v *time.Time) *ServiceContractUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ServiceContractUpdate) ClearEndDate() *ServiceContractUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetDurationMonths sets the "duration_months" field.
func (_u *ServiceContractUpdate) SetDurationMonths(v int) *ServiceContractUpdate {
	_u.mutation.ResetDurationMonths()
	_u.mutation.SetDurationMonths(v)
	return _u
}

// SetNillableDurationMonths sets the "duration_months" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableDurationMonths(v *int) *ServiceContractUpdate {
	if v != nil {
		_u.SetDurationMonths(*v)
	}
	return _u
}

// AddDurationMonths adds value to the "duration_months" field.
func (_u *ServiceContractUpdate) AddDurationMonths(v int) *ServiceContractUpdate {
	_u.mutation.AddDurationMonths(v)
	return _u
}

// ClearDurationMonths clears the value of the "duration_months" field.
func (_u *ServiceContractUpdate) ClearDurationMonths() *ServiceContractUpdate {
	_u.mutation.ClearDurationMonths()
	return _u
}

// SetDeliverables sets the "deliverables" field.
func (_u *ServiceContractUpdate) SetDeliverables(v string) *ServiceContractUpdate {
	_u.mutation.SetDeliverables(v)
	return _u
}

// SetNillableDeliverables sets the "deliverables" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableDeliverables(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetDeliverables(*v)
	}
	return _u
}

// ClearDeliverables clears the value of the "deliverables" field.
func (_u *ServiceContractUpdate) ClearDeliverables() *ServiceContractUpdate {
	_u.mutation.ClearDeliverables()
	return _u
}

// SetSLA sets the "sla" field.
func (_u *ServiceContractUpdate) SetSLA(v string) *ServiceContractUpdate {
	_u.mutation.SetSLA(v)
	return _u
}

// SetNillableSLA sets the "sla" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableSLA(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetSLA(*v)
	}
	return _u
}

// ClearSLA clears the value of the "sla" field.
func (_u *ServiceContractUpdate) ClearSLA() *ServiceContractUpdate {
	_u.mutation.ClearSLA()
	return _u
}

// SetPenalties sets the "penalties" field.
func (_u *ServiceContractUpdate) SetPenalties(v string) *ServiceContractUpdate {
	_u.mutation.SetPenalties(v)
	return _u
}

// SetNillablePenalties sets the "penalties" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillablePenalties(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetPenalties(*v)
	}
	return _u
}

// ClearPenalties clears the value of the "penalties" field.
func (_u *ServiceContractUpdate) ClearPenalties() *ServiceContractUpdate {
	_u.mutation.ClearPenalties()
	return _u
}

// SetPaymentTerms sets the "payment_terms" field.
func (_u *ServiceContractUpdate) SetPaymentTerms(v string) *ServiceContractUpdate {
	_u.mutation.SetPaymentTerms(v)
	return _u
}

// SetNillablePaymentTerms sets the "payment_terms" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillablePaymentTerms(v *string) *ServiceContractUpdate {
	if v != nil {
		_u.SetPaymentTerms(*v)
	}
	return _u
}

// ClearPaymentTerms clears the value of the "payment_terms" field.
func (_u *ServiceContractUpdate) ClearPaymentTerms() *ServiceContractUpdate {
	_u.mutation.ClearPaymentTerms()
	return _u
}

// SetAutoRenew sets the "auto_renew" field.
func (_u *ServiceContractUpdate) SetAutoRenew(v bool) *ServiceContractUpdate {
	_u.mutation.SetAutoRenew(v)
	return _u
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableAutoRenew(v *bool) *ServiceContractUpdate {
	if v != nil {
		_u.SetAutoRenew(*v)
	}
	return _u
}

// SetNextRenewalAt sets the "next_renewal_at" field.
func (_u *ServiceContractUpdate) SetNextRenewalAt(v time.Time) *ServiceContractUpdate {
	_u.mutation.SetNextRenewalAt(v)
	return _u
}

// SetNillableNextRenewalAt sets the "next_renewal_at" field if the given value is not nil.
func (_u *ServiceContractUpdate) SetNillableNextRenewalAt(v *time.Time) *ServiceContractUpdate {
	if v != nil {
		_u.SetNextRenewalAt(*v)
	}
	return _u
}

// ClearNextRenewalAt clears the value of the "next_renewal_at" field.
func (_u *ServiceContractUpdate) ClearNextRenewalAt() *ServiceContractUpdate {
	_u.mutation.ClearNextRenewalAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceContractUpdate) SetUpdatedAt(v time.Time) *ServiceContractUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ServiceContractMutation object of the builder.
func (_u *ServiceContractUpdate) Mutation() *ServiceContractMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceContractUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceContractUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceContractUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceContractUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceContractUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicecontract.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceContractUpdate) check() error {
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := servicecontract.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomerID(); ok {
		if err := servicecontract.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContractType(); ok {
		if err := servicecontract.ContractTypeValidator(v); err != nil {
			return &ValidationError{Name: "contract_type", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.contract_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := servicecontract.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := servicecontract.AmountCentsValidator(uint64(v)); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.amount_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingType(); ok {
		if err := servicecontract.BillingTypeValidator(v); err != nil {
			return &ValidationError{Name: "billing_type", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.billing_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := servicecontract.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceContractUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecontract.Table, servicecontract.Columns, sqlgraph.NewFieldSpec(servicecontract.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(servicecontract.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(servicecontract.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractType(); ok {
		_spec.SetField(servicecontract.FieldContractType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(servicecontract.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(servicecontract.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(servicecontract.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.BillingType(); ok {
		_spec.SetField(servicecontract.FieldBillingType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(servicecontract.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(servicecontract.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(servicecontract.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(servicecontract.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMonths(); ok {
		_spec.SetField(servicecontract.FieldDurationMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMonths(); ok {
		_spec.AddField(servicecontract.FieldDurationMonths, field.TypeInt, value)
	}
	if _u.mutation.DurationMonthsCleared() {
		_spec.ClearField(servicecontract.FieldDurationMonths, field.TypeInt)
	}
	if value, ok := _u.mutation.Deliverables(); ok {
		_spec.SetField(servicecontract.FieldDeliverables, field.TypeString, value)
	}
	if _u.mutation.DeliverablesCleared() {
		_spec.ClearField(servicecontract.FieldDeliverables, field.TypeString)
	}
	if value, ok := _u.mutation.SLA(); ok {
		_spec.SetField(servicecontract.FieldSLA, field.TypeString, value)
	}
	if _u.mutation.SLACleared() {
		_spec.ClearField(servicecontract.FieldSLA, field.TypeString)
	}
	if value, ok := _u.mutation.Penalties(); ok {
		_spec.SetField(servicecontract.FieldPenalties, field.TypeString, value)
	}
	if _u.mutation.PenaltiesCleared() {
		_spec.ClearField(servicecontract.FieldPenalties, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTerms(); ok {
		_spec.SetField(servicecontract.FieldPaymentTerms, field.TypeString, value)
	}
	if _u.mutation.PaymentTermsCleared() {
		_spec.ClearField(servicecontract.FieldPaymentTerms, field.TypeString)
	}
	if value, ok := _u.mutation.AutoRenew(); ok {
		_spec.SetField(servicecontract.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NextRenewalAt(); ok {
		_spec.SetField(servicecontract.FieldNextRenewalAt, field.TypeTime, value)
	}
	if _u.mutation.NextRenewalAtCleared() {
		_spec.ClearField(servicecontract.FieldNextRenewalAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicecontract.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceContractUpdateOne is the builder for updating a single ServiceContract entity.
type ServiceContractUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceContractMutation
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ServiceContractUpdateOne) SetOwnerUserID(v string) *ServiceContractUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableOwnerUserID(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *ServiceContractUpdateOne) SetCustomerID(v string) *ServiceContractUpdateOne {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableCustomerID(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// SetContractType sets the "contract_type" field.
func (_u *ServiceContractUpdateOne) SetContractType(v string) *ServiceContractUpdateOne {
	_u.mutation.SetContractType(v)
	return _u
}

// SetNillableContractType sets the "contract_type" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableContractType(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetContractType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ServiceContractUpdateOne) SetTitle(v string) *ServiceContractUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableTitle(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *ServiceContractUpdateOne) SetAmountCents(v uint64) *ServiceContractUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableAmountCents(v *uint64) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *ServiceContractUpdateOne) AddAmountCents(v uint64) *ServiceContractUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetBillingType sets the "billing_type" field.
func (_u *ServiceContractUpdateOne) SetBillingType(v string) *ServiceContractUpdateOne {
	_u.mutation.SetBillingType(v)
	return _u
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableBillingType(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetBillingType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ServiceContractUpdateOne) SetStatus(v string) *ServiceContractUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableStatus(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ServiceContractUpdateOne) SetStartDate(v time.Time) *ServiceContractUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableStartDate(v *time.Time) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ServiceContractUpdateOne) SetEndDate(v time.Time) *ServiceContractUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableEndDate(v *time.Time) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ServiceContractUpdateOne) ClearEndDate() *ServiceContractUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetDurationMonths sets the "duration_months" field.
func (_u *ServiceContractUpdateOne) SetDurationMonths(v int) *ServiceContractUpdateOne {
	_u.mutation.ResetDurationMonths()
	_u.mutation.SetDurationMonths(v)
	return _u
}

// SetNillableDurationMonths sets the "duration_months" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableDurationMonths(v *int) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetDurationMonths(*v)
	}
	return _u
}

// AddDurationMonths adds value to the "duration_months" field.
func (_u *ServiceContractUpdateOne) AddDurationMonths(v int) *ServiceContractUpdateOne {
	_u.mutation.AddDurationMonths(v)
	return _u
}

// ClearDurationMonths clears the value of the "duration_months" field.
func (_u *ServiceContractUpdateOne) ClearDurationMonths() *ServiceContractUpdateOne {
	_u.mutation.ClearDurationMonths()
	return _u
}

// SetDeliverables sets the "deliverables" field.
func (_u *ServiceContractUpdateOne) SetDeliverables(v string) *ServiceContractUpdateOne {
	_u.mutation.SetDeliverables(v)
	return _u
}

// SetNillableDeliverables sets the "deliverables" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableDeliverables(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetDeliverables(*v)
	}
	return _u
}

// ClearDeliverables clears the value of the "deliverables" field.
func (_u *ServiceContractUpdateOne) ClearDeliverables() *ServiceContractUpdateOne {
	_u.mutation.ClearDeliverables()
	return _u
}

// SetSLA sets the "sla" field.
func (_u *ServiceContractUpdateOne) SetSLA(v string) *ServiceContractUpdateOne {
	_u.mutation.SetSLA(v)
	return _u
}

// SetNillableSLA sets the "sla" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableSLA(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetSLA(*v)
	}
	return _u
}

// ClearSLA clears the value of the "sla" field.
func (_u *ServiceContractUpdateOne) ClearSLA() *ServiceContractUpdateOne {
	_u.mutation.ClearSLA()
	return _u
}

// SetPenalties sets the "penalties" field.
func (_u *ServiceContractUpdateOne) SetPenalties(v string) *ServiceContractUpdateOne {
	_u.mutation.SetPenalties(v)
	return _u
}

// SetNillablePenalties sets the "penalties" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillablePenalties(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetPenalties(*v)
	}
	return _u
}

// ClearPenalties clears the value of the "penalties" field.
func (_u *ServiceContractUpdateOne) ClearPenalties() *ServiceContractUpdateOne {
	_u.mutation.ClearPenalties()
	return _u
}

// SetPaymentTerms sets the "payment_terms" field.
func (_u *ServiceContractUpdateOne) SetPaymentTerms(v string) *ServiceContractUpdateOne {
	_u.mutation.SetPaymentTerms(v)
	return _u
}

// SetNillablePaymentTerms sets the "payment_terms" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillablePaymentTerms(v *string) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetPaymentTerms(*v)
	}
	return _u
}

// ClearPaymentTerms clears the value of the "payment_terms" field.
func (_u *ServiceContractUpdateOne) ClearPaymentTerms() *ServiceContractUpdateOne {
	_u.mutation.ClearPaymentTerms()
	return _u
}

// SetAutoRenew sets the "auto_renew" field.
func (_u *ServiceContractUpdateOne) SetAutoRenew(v bool) *ServiceContractUpdateOne {
	_u.mutation.SetAutoRenew(v)
	return _u
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableAutoRenew(v *bool) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetAutoRenew(*v)
	}
	return _u
}

// SetNextRenewalAt sets the "next_renewal_at" field.
func (_u *ServiceContractUpdateOne) SetNextRenewalAt(v time.Time) *ServiceContractUpdateOne {
	_u.mutation.SetNextRenewalAt(v)
	return _u
}

// SetNillableNextRenewalAt sets the "next_renewal_at" field if the given value is not nil.
func (_u *ServiceContractUpdateOne) SetNillableNextRenewalAt(v *time.Time) *ServiceContractUpdateOne {
	if v != nil {
		_u.SetNextRenewalAt(*v)
	}
	return _u
}

// ClearNextRenewalAt clears the value of the "next_renewal_at" field.
func (_u *ServiceContractUpdateOne) ClearNextRenewalAt() *ServiceContractUpdateOne {
	_u.mutation.ClearNextRenewalAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceContractUpdateOne) SetUpdatedAt(v time.Time) *ServiceContractUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ServiceContractMutation object of the builder.
func (_u *ServiceContractUpdateOne) Mutation() *ServiceContractMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServiceContractUpdate builder.
func (_u *ServiceContractUpdateOne) Where(ps ...predicate.ServiceContract) *ServiceContractUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceContractUpdateOne) Select(field string, fields ...string) *ServiceContractUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceContract entity.
func (_u *ServiceContractUpdateOne) Save(ctx context.Context) (*ServiceContract, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceContractUpdateOne) SaveX(ctx context.Context) *ServiceContract {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceContractUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceContractUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceContractUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := servicecontract.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceContractUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := servicecontract.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CustomerID(); ok {
		if err := servicecontract.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContractType(); ok {
		if err := servicecontract.ContractTypeValidator(v); err != nil {
			return &ValidationError{Name: "contract_type", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.contract_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := servicecontract.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := servicecontract.AmountCentsValidator(uint64(v)); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.amount_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillingType(); ok {
		if err := servicecontract.BillingTypeValidator(v); err != nil {
			return &ValidationError{Name: "billing_type", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.billing_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := servicecontract.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ServiceContract.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceContractUpdateOne) sqlSave(ctx context.Context) (_node *ServiceContract, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(servicecontract.Table, servicecontract.Columns, sqlgraph.NewFieldSpec(servicecontract.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceContract.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicecontract.FieldID)
		for _, f := range fields {
			if !servicecontract.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servicecontract.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(servicecontract.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(servicecontract.FieldCustomerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContractType(); ok {
		_spec.SetField(servicecontract.FieldContractType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(servicecontract.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(servicecontract.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(servicecontract.FieldAmountCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.BillingType(); ok {
		_spec.SetField(servicecontract.FieldBillingType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(servicecontract.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(servicecontract.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(servicecontract.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(servicecontract.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMonths(); ok {
		_spec.SetField(servicecontract.FieldDurationMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMonths(); ok {
		_spec.AddField(servicecontract.FieldDurationMonths, field.TypeInt, value)
	}
	if _u.mutation.DurationMonthsCleared() {
		_spec.ClearField(servicecontract.FieldDurationMonths, field.TypeInt)
	}
	if value, ok := _u.mutation.Deliverables(); ok {
		_spec.SetField(servicecontract.FieldDeliverables, field.TypeString, value)
	}
	if _u.mutation.DeliverablesCleared() {
		_spec.ClearField(servicecontract.FieldDeliverables, field.TypeString)
	}
	if value, ok := _u.mutation.SLA(); ok {
		_spec.SetField(servicecontract.FieldSLA, field.TypeString, value)
	}
	if _u.mutation.SLACleared() {
		_spec.ClearField(servicecontract.FieldSLA, field.TypeString)
	}
	if value, ok := _u.mutation.Penalties(); ok {
		_spec.SetField(servicecontract.FieldPenalties, field.TypeString, value)
	}
	if _u.mutation.PenaltiesCleared() {
		_spec.ClearField(servicecontract.FieldPenalties, field.TypeString)
	}
	if value, ok := _u.mutation.PaymentTerms(); ok {
		_spec.SetField(servicecontract.FieldPaymentTerms, field.TypeString, value)
	}
	if _u.mutation.PaymentTermsCleared() {
		_spec.ClearField(servicecontract.FieldPaymentTerms, field.TypeString)
	}
	if value, ok := _u.mutation.AutoRenew(); ok {
		_spec.SetField(servicecontract.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NextRenewalAt(); ok {
		_spec.SetField(servicecontract.FieldNextRenewalAt, field.TypeTime, value)
	}
	if _u.mutation.NextRenewalAtCleared() {
		_spec.ClearField(servicecontract.FieldNextRenewalAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicecontract.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ServiceContract{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicecontract.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
