// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aggi-tech/aggipay/ent/predicate"
	"github.com/aggi-tech/aggipay/ent/servicecontract"
)

// ServiceContractDelete is the builder for deleting a ServiceContract entity.
type ServiceContractDelete struct {
	config
	hooks    []Hook
	mutation *ServiceContractMutation
}

// Where appends a list predicates to the ServiceContractDelete builder.
func (_d *ServiceContractDelete) Where(ps ...predicate.ServiceContract) *ServiceContractDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ServiceContractDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceContractDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ServiceContractDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(servicecontract.Table, sqlgraph.NewFieldSpec(servicecontract.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ServiceContractDeleteOne is the builder for deleting a single ServiceContract entity.
type ServiceContractDeleteOne struct {
	_d *ServiceContractDelete
}

// Where appends a list predicates to the ServiceContractDelete builder.
func (_d *ServiceContractDeleteOne) Where(ps ...predicate.ServiceContract) *ServiceContractDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ServiceContractDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{servicecontract.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceContractDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
