// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/worklog"
)

// Worklog is the model entity for the Worklog schema.
type Worklog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// MilestoneID holds the value of the "milestone_id" field.
	MilestoneID *string `json:"milestone_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Hours holds the value of the "hours" field.
	Hours float64 `json:"hours,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// WorkedAt holds the value of the "worked_at" field.
	WorkedAt time.Time `json:"worked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Worklog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case worklog.FieldHours:
			values[i] = new(sql.NullFloat64)
		case worklog.FieldID, worklog.FieldProjectID, worklog.FieldMilestoneID, worklog.FieldUserID, worklog.FieldDescription:
			values[i] = new(sql.NullString)
		case worklog.FieldWorkedAt, worklog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Worklog fields.
func (_m *Worklog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case worklog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = string(value.String)
			}
		case worklog.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case worklog.FieldMilestoneID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field milestone_id", values[i])
			} else if value.Valid {
				_m.MilestoneID = new(string)
				*_m.MilestoneID = value.String
			}
		case worklog.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case worklog.FieldHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hours", values[i])
			} else if value.Valid {
				_m.Hours = value.Float64
			}
		case worklog.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case worklog.FieldWorkedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field worked_at", values[i])
			} else if value.Valid {
				_m.WorkedAt = value.Time
			}
		case worklog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Worklog.
// This includes values selected through modifiers, order, etc.
func (_m *Worklog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Worklog.
// Note that you need to call Worklog.Unwrap() before calling this method if this Worklog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Worklog) Update() *WorklogUpdateOne {
	return NewWorklogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Worklog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Worklog) Unwrap() *Worklog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Worklog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Worklog) String() string {
	var builder strings.Builder
	builder.WriteString("Worklog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	if v := _m.MilestoneID; v != nil {
		builder.WriteString("milestone_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hours))
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("worked_at=")
	builder.WriteString(_m.WorkedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Worklogs is a parsable slice of Worklog.
type Worklogs []*Worklog
