// Code generated by ent, DO NOT EDIT.

package worklog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/aggi-tech/aggipay/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldProjectID, v))
}

// MilestoneID applies equality check predicate on the "milestone_id" field. It's identical to MilestoneIDEQ.
func MilestoneID(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldMilestoneID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldUserID, v))
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldHours, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldDescription, v))
}

// WorkedAt applies equality check predicate on the "worked_at" field. It's identical to WorkedAtEQ.
func WorkedAt(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldWorkedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldCreatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldProjectID, v))
}

// MilestoneIDEQ applies the EQ predicate on the "milestone_id" field.
func MilestoneIDEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldMilestoneID, v))
}

// MilestoneIDNEQ applies the NEQ predicate on the "milestone_id" field.
func MilestoneIDNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldMilestoneID, v))
}

// MilestoneIDIn applies the In predicate on the "milestone_id" field.
func MilestoneIDIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldMilestoneID, vs...))
}

// MilestoneIDNotIn applies the NotIn predicate on the "milestone_id" field.
func MilestoneIDNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldMilestoneID, vs...))
}

// MilestoneIDGT applies the GT predicate on the "milestone_id" field.
func MilestoneIDGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldMilestoneID, v))
}

// MilestoneIDGTE applies the GTE predicate on the "milestone_id" field.
func MilestoneIDGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldMilestoneID, v))
}

// MilestoneIDLT applies the LT predicate on the "milestone_id" field.
func MilestoneIDLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldMilestoneID, v))
}

// MilestoneIDLTE applies the LTE predicate on the "milestone_id" field.
func MilestoneIDLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldMilestoneID, v))
}

// MilestoneIDContains applies the Contains predicate on the "milestone_id" field.
func MilestoneIDContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldMilestoneID, v))
}

// MilestoneIDHasPrefix applies the HasPrefix predicate on the "milestone_id" field.
func MilestoneIDHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldMilestoneID, v))
}

// MilestoneIDHasSuffix applies the HasSuffix predicate on the "milestone_id" field.
func MilestoneIDHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldMilestoneID, v))
}

// MilestoneIDIsNil applies the IsNil predicate on the "milestone_id" field.
func MilestoneIDIsNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldIsNull(FieldMilestoneID))
}

// MilestoneIDNotNil applies the NotNil predicate on the "milestone_id" field.
func MilestoneIDNotNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldNotNull(FieldMilestoneID))
}

// MilestoneIDEqualFold applies the EqualFold predicate on the "milestone_id" field.
func MilestoneIDEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldMilestoneID, v))
}

// MilestoneIDContainsFold applies the ContainsFold predicate on the "milestone_id" field.
func MilestoneIDContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldMilestoneID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldUserID, v))
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldHours, v))
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldHours, v))
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldHours, vs...))
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldHours, vs...))
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldHours, v))
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldHours, v))
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldHours, v))
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldHours, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Worklog {
	return predicate.Worklog(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Worklog {
	return predicate.Worklog(sql.FieldContainsFold(FieldDescription, v))
}

// WorkedAtEQ applies the EQ predicate on the "worked_at" field.
func WorkedAtEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldWorkedAt, v))
}

// WorkedAtNEQ applies the NEQ predicate on the "worked_at" field.
func WorkedAtNEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldWorkedAt, v))
}

// WorkedAtIn applies the In predicate on the "worked_at" field.
func WorkedAtIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldWorkedAt, vs...))
}

// WorkedAtNotIn applies the NotIn predicate on the "worked_at" field.
func WorkedAtNotIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldWorkedAt, vs...))
}

// WorkedAtGT applies the GT predicate on the "worked_at" field.
func WorkedAtGT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldWorkedAt, v))
}

// WorkedAtGTE applies the GTE predicate on the "worked_at" field.
func WorkedAtGTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldWorkedAt, v))
}

// WorkedAtLT applies the LT predicate on the "worked_at" field.
func WorkedAtLT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldWorkedAt, v))
}

// WorkedAtLTE applies the LTE predicate on the "worked_at" field.
func WorkedAtLTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldWorkedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Worklog {
	return predicate.Worklog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Worklog) predicate.Worklog {
	return predicate.Worklog(sql.NotPredicates(p))
}
